llm:
  provider: openai
  model: qwen-plus
  ollama_model: llama3.1:8b
  openai_model: gpt-4
  openai_base_url: 'https://api.gptsapi.net/v1'
  timeout: 60.0
  system_prompt_template: |
    You are a chat bot designed to answer questions about the company and the products and services they offer.

default_checklist: []
