functions:
  configs:
    retrieval_service_search:
      api_url: http://localhost:8001
      max_search_iterations: 3
      pipeline_name: default
      timeout: 30
  enabled:
  - faq_search
  - retrieval_service_search
